apiVersion: v1
kind: Pod
metadata:
  namespace: argocd-gitops
  name: nginx
  labels:
    role: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  
---
apiVersion: v1
kind: Service
metadata:
  namespace: argocd-gitops
  name: argocd-gitops-svc
#  labels:
#    role: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    role: nginx
  type: NodePort
